name: 'Create Nightly Release'
description: 'Create nightly release and upload new artifacts'
author: 'Andelf'
inputs:
  tag_name:
    description: 'The name of the tag.'
    required: true
    default: 'nightly'

  release_id:
    required: true

  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
