name: 'Update Nightly Release'
description: 'Update the nightly release, remove old artifacts and upload new artifacts'
author: 'andelf'
inputs:
  tag_name:
    description: 'The name of the tag. Will be overwrite by current ref'
    required: true
    default: 'nightly'

  release_id:
    description: 'The id of the release'
    required: false

  name:
    description: 'The name of the release'
    required: false
    default: 'Nightly Release @ $$'

  #commitish:
  #  description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
  #  required: false

  body:
    description: "Note-worthy description of changes in release"
    required: false
  body_path:
    description: "Path to load note-worthy description of changes in release from"
    required: false

  files:
    description: "Newline-delimited list of path globs for asset files to upload"
    required: false

  keep_old_files:
    description: "Keep old artifacts?  Defaults to true"
    default: true

  draft:
    description: "Creates a draft release. Defaults to false"
    required: false
    default: false
  prerelease:
    description: "Identify the release as a prerelease. Defaults to true"
    required: false
    default: true
env:
  "GITHUB_TOKEN": "As provided by Github Actions"
runs:
  using: 'node16'
  main: 'dist/index.js'
